services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/paroquia_db?sslmode=disable

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # A seção 'volumes' foi removida para garantir que os arquivos da imagem sejam usados.
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paroquia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

