services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80" 
    depends_on:
      - backend
    restart: always
    # A CORREÇÃO CRUCIAL:
    # Passamos a URL pública do backend (do seu Codespaces) para o React.
    environment:
      - REACT_APP_API_BASE_URL=https://glorious-palm-tree-g4p549q76rqg29q96-8080.app.github.dev

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=paroquia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d paroquia_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

