services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build: ./frontend
    ports:
      # Nginx serve na porta 80 por padrão. Mapeamos para 3000 para o Codespaces.
      - "3000:80" 
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=paroquia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d paroquia_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

